version: '3'
services:
  gbm-challenges-server:
    image: mysql:8.0.28-oracle
    environment:
      MYSQL_ROOT_PASSWORD: cvillarreal1990
      MYSQL_DATABASE: gbm_challenge
    ports:
      - "3306:3306"
  admin:
    image: adminer
    ports:
      - "8080:8080"